apiVersion: apps/v1
kind: Deployment
metadata:
  name: roadquality-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roadquality-frontend
  template:
    metadata:
      labels:
        app: roadquality-frontend
    spec:
      containers:
        - name: frontend
          image: iot-arduino-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80