apiVersion: apps/v1
kind: Deployment
metadata:
  name: roadquality-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roadquality-api
  template:
    metadata:
      labels:
        app: roadquality-api
    spec:
      containers:
        - name: api
          image: iot-arduino-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000